name: Audio_Enhancement_CNN
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.3
  - torchaudio=2.3
  - pytorch-cuda=12.1
  - pip
  - jupyter
  - jupyterlab
  - numpy
  - matplotlib
  - scipy
  - pyyaml
  - pip:
      - librosa
      - soundfile
      - soxr
      - pesq
      - pystoi
      - tqdm
      - tensorboard
      - einops
      - requests